baseURL = "/"
languageCode = "fr-FR"
title = "Nootim"
theme = "ananke"
DefaultContentLanguage = "fr"
SectionPagesMenu = "main"
Paginate = 3 # this is set low for demonstrating with dummy content. Set to a higher number

[params]
    background_color_class = "bg-blue"
