baseURL = "/"
languageCode = "fr-FR"
title = "Nootim"
theme = "ananke"
DefaultContentLanguage = "fr"
SectionPagesMenu = "main"
Paginate = 6 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = "UA-89707126-2"



[params]
    background_color_class = "bg-blue"
    description = "Articles sur le développement web"
